- name: ansible play to create ec instances and dns records
  hosts: local
  connection: local
  vars:
    sg_id: sg-03b441e0ba008f925
    ami_id: ami-0220d79f3f480ecf5
    dns: rscloudservices.icu
    instances:
     - mongodb
     - catalogue
     - frontend
     - redis
     - user
     - cart
     - mysql
     - shipping
     - rabbitmq
     - payment
  tasks:
    - name: create ec2 instances
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        image_id: "{{ ami_id }}"
        security_group: "{{ sg_id }}"
        instance_type: t3.micro
        tags:
          Name: "{{ item }}"
      loop: "{{ instances }}"
      register: ec2_output
