- name: Ansible playbook to create instances and update r53 records
  hosts: local
  connection: local
  vars:
    servers: 
      - mongodb
      - catalogue
      - redis
      - user
      - cart
      - mysql
      - shipping
      - rabbitmq
      - payment
      - dispatch
      - frontend
  tasks:
    - name: Install dependencies
      become: yes
      ansible.builtin.dnf:
        name: 
         - python3
         - python3-pip
        state: present
    - name: Install dependency_libraries
      become: yes
      ansible.builtin.pip:
        name: 
         - boto3
         - botocore
        executable: pip3
        state: present
    - name: Create instances
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        instance_type: t3.micro
        security_groups:
          - sg-03b441e0ba008f925
        image_id: ami-0220d79f3f480ecf5
        tags:
          Name: "{{ item }}"
          Environment: Dev
      loop: "{{ servers }}"
      register: ec2_output
    - name: Print ec2_output
      ansible.builtin.debug:
       msg: "{{ ec2_output }}"